### ISSUE TITLE
Try bpaf for arg parsing

### ISSUE THREAD

**Issue by crispinb** [crispinb/cvcap#36]
https://github.com/pacak/bpaf

I've always been unhappy with clap. This might be a good alternative. Great docs, principled api.

**Comment by pacak** [comment]
Mostly trying to mechanically encode  "required_unless_present", "conflicts_with" in terms of algebraic products and sums.
```diff
-#[derive(Debug, Args)]
-pub struct AddTaskCommand {
-    #[clap(
-        name = "task text",
-        required_unless_present = "from clipboard",
-        required_unless_present = "from stdin"
-    )]
-    task_content: Option<String>,
-    /// Choose a list to add a new task to (ie. other than your default list)
-    #[clap(
-        name = "choose list",
-        short = 'l',
-        long,
-        conflicts_with = "quiet",
-        conflicts_with = "bookmark"
-    )]
-    choose_list: bool,
-    /// Add a task from the clipboard instead of the command line
-    #[clap(
-        short = 'c',
-        long,
-        name = "from clipboard",
-        conflicts_with = "task text",
-        conflicts_with = "from stdin"
-    )]
-    from_clipboard: bool,
-    /// Add a task from stdin instead of the command line
-    #[clap(
-        name = "from stdin",
-        short = 's',
-        long,
-        conflicts_with = "task text",
-        conflicts_with = "from clipboard"
-    )]
-    from_stdin: bool,
-    /// Add task to custom location instead of top of default list
-    /// (bookmark must exist in config file)
-    #[clap(short = 'b', long = "bookmark", conflicts_with = "choose list")]
-    pub bookmark: Option<String>,
-}
+#[derive(Debug, Clone, Bpaf)]
+#[bpaf(command("add"))]
+pub struct AddTaskCommand {
+    #[bpaf(external)]
+    add_from: AddFrom,
+    #[bpaf(external)]
+    add_to: AddTo,
+}
+
+#[derive(Debug, Clone, Bpaf)]
+pub enum AddFrom {
+    TextTask {
+        #[bpaf(positional)]
+        content: String,
+    },
+    /// Add a task from stdin instead of the command line
+    #[bpaf(short, long)]
+    FromStdin,
+
+    /// Add a task from the clipboard instead of the command line
+    #[bpaf(short('c'), long)]
+    FromClipboard,
+}
+
+#[derive(Debug, Clone, Bpaf)]
+#[bpaf(fallback(AddTo::Unspecified))]
+pub enum AddTo {
+    /// Choose a list to add a new task to (ie. other than your default list)
+    #[bpaf(short, long)]
+    ChooseList,
+
+    /// Add task to custom location instead of top of default list
+    /// (bookmark must exist in config file)
+    Bookmark {
+        #[bpaf(short, long)]
+        bookmark: String,
+    },
+    #[bpaf(hide)]
+    Unspecified, 
+}
```
Unfortunately also requires a bunch of changes to the code itself, but on the other hand removes `panic!` calls like this one...

```rust
    /// Get content from args, clipboard or std, depending on user-provided options
    /// Owns self to avoid cloning the content
    fn get_task_content(self, allow_interaction: bool) -> Result<String> {
        match (self.from_clipboard, self.from_stdin) {
            (true, false) => self.get_content_from_clipboard(allow_interaction),
            (false, true) => self.get_content_from_stdin(),
            (false, false) => self
                .task_content
                .ok_or_else(|| AddTaskError::Unhandled(anyhow!("Task content cannot be empty"))),

            (true, true) => panic!("Argument parsing failed"),
        }
    }
```

**Comment by crispinb** [comment]
Thanks! That's a great starting point for when I get to this issue.

I see your point about the panic. I thought it OK in this instance since as far as I can see you'd only ever get there if there was a bug in clap. 

But I'm quite happy to rework much of the code in any case. This is my first real-ish Rust project and my use of the language is pretty elementary (euphemism, much?).

**Comment by pacak** [comment]
With that panic you are not using the power of rust types to your advantage. Say you want to add one more input type, my to go example is [this](https://github.com/pacak/cargo-show-asm/blob/d1b7acf84bc1c557b9ab369107abeae126a192fc/src/opts.rs#L227). with enum compiler will point out all the places you need to update the code, with struct - good luck, you are on your own.

Try removing all the annotations from both examples to see what invariants type system helps you to enforce

This only lists the arguments you might get
```rust
#[derive(Debug)]
pub struct AddTaskCommand {
    task_content: Option<String>,
    /// Choose a list to add a new task to (ie. other than your default list)
    choose_list: bool,
    /// Add a task from the clipboard instead of the command line
    from_clipboard: bool,
    /// Add a task from stdin instead of the command line
    from_stdin: bool,
    /// Add task to custom location instead of top of default list
    /// (bookmark must exist in config file)
    pub bookmark: Option<String>,
}
```
This lists scenarios (as much as I managed to understand them, I could be wrong), their mutual exclusivity and relationship to each other.
```rust
#[derive(Debug, Clone)]
pub struct AddTaskCommand {
    add_from: AddFrom,
    add_to: AddTo,
}

#[derive(Debug, Clone)]
pub enum AddFrom {
    TextTask { content: String },
    /// Add a task from stdin instead of the command line
    FromStdin,
    /// Add a task from the clipboard instead of the command line
    FromClipboard,
}

#[derive(Debug, Clone)]
pub enum AddTo {
    /// Choose a list to add a new task to (ie. other than your default list)
    ChooseList,
    /// Add task to custom location instead of top of default list
    /// (bookmark must exist in config file)
    Bookmark { bookmark: String },
    Unspecified, 
}
```

And finally there's this article, it's in Haskell but types are similar: https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/

**Comment by crispinb** [comment]
Yes I get the drift.  I kept hitting limitations in my ability to model the UI I wanted purely with types using clap, so had to add a few runtime wrinkles here and there. I'm sure it was my own fault - arg parsing isn't exactly the most interesting part of writing an app so I wanted to get it out of the way, and jumped straight into using clap's `derive` without looking much into the  Builder api. So I didn't have much insight into how it was all working under the hood.

I'm actually going to use bpaf's combinatorial api to start with, so as not to repeat that mistake.

**Comment by pacak** [comment]
> I'm actually going to use bpaf's combinatorial api to start with, so as not to repeat that mistake.

You don't have to. With bpaf you don't have to choose between combinatoric or derive API, you can use a mix of both. In fact derive API is a very thin layer of syntactic sugar on top of combinatoric API - you can see what I mean if you expand derives with help of rust-analyzer.

**Comment by crispinb** [comment]
Yes but it's not so much a matter of choosing - more that I find it hard to understand apis without exercising them. I imagine the derive api will be more convenient for some things once I have a bit of conceptual fluency.

**Comment by pacak** [comment]
Derive API just saves you some typing :)

Have you seen the article? https://rustmagazine.org/issue-2/applicative-parsing/

**Comment by crispinb** [comment]
No I hadn't but I'll give it a read. Thanks.

**Comment by pacak** [comment]
`zip` from the article corresponds to making any `struct` or `enum` variants in derive api but also most of the `construct!` invocations except for those with `[]` inside, `alt` corresponds to choosing between `enum` variants and `construct!([...])` things.

**Comment by crispinb** [comment]
Thanks, that was all extremely helpful.
