### ISSUE TITLE
`-q` should be mutually exclusive with `-l`

### ISSUE THREAD

**Issue by crispinb** [crispinb/cvcap#39]
eg. `cvcap add 'task' -l -q` shouldn't parse.

I think a guard on `-q`?

**Comment by pacak** [comment]
Your options are either using `guard` or moving things around a bit and make it so in a place where you care - you parse both `-q` and `-l` into a single `enum`.

For later you'll have your `interactivity_level` inside each command and inside `add` - slightly more customized.

**Comment by crispinb** [comment]
Thanks yes - I think I prefer type-modelling approach on principle, but in this case will opt for the simpler `guard` escape hatch.

Btw - that was a question for myself. I'm not expecting you to coach me through every `bpaf`-related issue! But many thanks for the help.

**Comment by crispinb** [comment]
Fixed in b1a1032
