### ISSUE TITLE
Binaries would be nice

### ISSUE THREAD

**Issue by zinoff** [crispinb/cvcap#46]
cvcap seems to be perfect for using Alfred on Mac to do quick entry on Checkvist, but would prefer not having to install Rust (as I don't know it).

**Comment by zinoff** [comment]
actually it took about 5 minutes to download Rust and compile, so consider it closed.

**Comment by crispinb** [comment]
@zinoff I know you've closed this, but just thought I'd mention that this repo is essentially abandoned. I'm out of the programming game these days. So there won't be any more updates or bug fixes. It was a useful project so it would be nice if someone picked it up some time, but given the seemingly small reach of Checkvist, I wouldn't hold my breath.

I did have builds at an earlier stage but they proved fragile. I had planned to reinstate them at some point: https://github.com/crispinb/cvcap/issues/40
